table_name: hire_employee
description: Hire Employee table in human_resources domain.
columns:
- name: employee_id_associate_id
  business_name: Employee ID (Associate ID)
  physical_name: employee_id_associate_id
  logical_type: Text
  physical_type: Text
  required: true
  nullable: false
  primary_key: true
  unique: true
  identifier_type: Primary Key
  description: ''
  source_column: Employee Number
  sample_values: []
  tags: []
- name: hire_subcategory_reason
  business_name: Hire Subcategory Reason
  physical_name: hire_subcategory_reason
  logical_type: Text
  physical_type: Text
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: Event Reason
  sample_values: []
  tags: []
- name: first_day_of_work
  business_name: First Day of Work
  physical_name: first_day_of_work
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: Most Recent Start Date
  sample_values: []
  tags: []
- name: hire_date
  business_name: Hire Date
  physical_name: hire_date
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: The worker's most recent hire date. This report field cannot be effective dated.
  source_column: Most Recent Start Date
  sample_values: []
  tags: []
- name: continuous_service_date
  business_name: Continuous Service Date
  physical_name: continuous_service_date
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: Associate service date taking into account breaks in service.
  source_column: Adjusted Seniority Date
  sample_values: []
  tags: []
- name: probation_start_date
  business_name: Probation Start Date
  physical_name: probation_start_date
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: Most Recent Start Date
  sample_values: []
  tags: []
- name: probation_end_date
  business_name: Probation End Date
  physical_name: probation_end_date
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: Probation Period End Date
  sample_values: []
  tags: []
- name: end_employment_date
  business_name: End Employment Date
  physical_name: end_employment_date
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: Contract End Date
  sample_values: []
  tags: []
- name: benefit_service_date
  business_name: Benefit Service Date
  physical_name: benefit_service_date
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: Pension Start Date
  sample_values: []
  tags: []
- name: company_service_date
  business_name: Company Service Date
  physical_name: company_service_date
  logical_type: dd-MMM-yyyy
  physical_type: dd-MMM-yyyy
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: Company Service Date for the Worker.
  source_column: Kellanova Service Date
  sample_values: []
  tags: []
- name: position_id
  business_name: Position ID
  physical_name: position_id
  logical_type: Text
  physical_type: Text
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: The unique identifier for the worker's primary position.
  source_column: Position ID
  sample_values: []
  tags: []
- name: job_code
  business_name: Job Code
  physical_name: job_code
  logical_type: Job_Profile_ID
  physical_type: Job_Profile_ID
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: ''
  source_column: Job Key
  sample_values: []
  tags: []
- name: position_title
  business_name: Position Title
  physical_name: position_title
  logical_type: Text
  physical_type: Text
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: The worker's primary position.
  source_column: Position Name
  sample_values: []
  tags: []
- name: business_title
  business_name: Business Title
  physical_name: business_title
  logical_type: Text
  physical_type: Text
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: The business title for the worker's primary position. If no business title is defined for a position, the position
    title is returned back.
  source_column: Position Title
  sample_values: []
  tags: []
- name: default_weekly_hours
  business_name: Default Weekly Hours
  physical_name: default_weekly_hours
  logical_type: Number
  physical_type: Number
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: 'The standard hours for the worker''s primary position.  Usually this is equal to the location standard hours
    but can be overridden at the position level.  This is used in the calculation for Full Time Equivalent: Scheduled Weekly
    Hours / Standard Weekly Hours.'
  source_column: Standard Weekly Hours (Job Key/Position)
  sample_values: []
  tags: []
- name: scheduled_weekly_hours
  business_name: Scheduled Weekly Hours
  physical_name: scheduled_weekly_hours
  logical_type: Number
  physical_type: Number
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: 'The weekly hours for the worker''s primary position.  This is used in the Full Time Equivalent calculation:
    Scheduled Weekly Hours / Standard Weekly Hours.'
  source_column: Standard Weekly Hours (Employee)
  sample_values: []
  tags: []
- name: pay_rate_type
  business_name: Pay Rate Type
  physical_name: pay_rate_type
  logical_type: Pay_Rate_Type_ID
  physical_type: Pay_Rate_Type_ID
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: The pay rate type for an associate's position and is used by payroll.
  source_column: Pay Type
  sample_values: []
  tags: []
- name: supervisory_organization_reference_id
  business_name: Supervisory Organization Reference ID
  physical_name: supervisory_organization_reference_id
  logical_type: Text
  physical_type: Text
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: ''
  source_column: Manager Employee ID/Position ID
  sample_values: []
  tags: []
- name: custom_organization_reference_id_2_personel_area
  business_name: Custom Organization Reference ID 2(Personel Area)
  physical_name: custom_organization_reference_id_2_personel_area
  logical_type: Custom_Organization_Reference_ID
  physical_type: Custom_Organization_Reference_ID
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: N/A
  sample_values: []
  tags: []
- name: custom_organization_reference_id_3_business_unit
  business_name: Custom Organization Reference ID 3(Business Unit)
  physical_name: custom_organization_reference_id_3_business_unit
  logical_type: Custom_Organization_Reference_ID
  physical_type: Custom_Organization_Reference_ID
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: N/A
  sample_values: []
  tags: []
- name: custom_organization_reference_id_4_product_department
  business_name: Custom Organization Reference ID 4(Product Department
  physical_name: custom_organization_reference_id_4_product_department
  logical_type: Custom_Organization_Reference_ID
  physical_type: Custom_Organization_Reference_ID
  required: false
  nullable: true
  primary_key: false
  unique: false
  description: ''
  source_column: N/A
  sample_values: []
  tags: []
