table_name: worker_national_id_data
description: Worker National ID Data table in the human_resources domain
columns:
- name: worker_id
  business_name: Worker ID
  physical_name: worker_id
  logical_type: Text
  physical_type: Text
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: ''
  source_column: Employee Number
  sample_values: []
  tags: []
- name: worker_type
  business_name: Worker Type
  physical_name: worker_type
  logical_type: EE/CW
  physical_type: EE/CW
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: ''
  source_column: Employee Class/Type & contract type
  sample_values: []
  tags: []
- name: national_id
  business_name: National ID
  physical_name: national_id
  logical_type: Text
  physical_type: Text
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: ''
  source_column: National ID
  sample_values: []
  tags: []
- name: national_id_type
  business_name: National ID Type
  physical_name: national_id_type
  logical_type: National_ID_Type_Code
  physical_type: National_ID_Type_Code
  required: true
  nullable: false
  primary_key: false
  unique: false
  description: ''
  source_column: National Id Card Type
  sample_values: []
  tags: []
